version: '3.8'

services:
  # 1. The Orchestrator (n8n)
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_ENCRYPTION_KEY=super-secret-key-12345
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      # Fixes for Codespaces Networking
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/home/node/.n8n
    links:
      - postgres
      - redis
      - brain

  # 2. The Database (Postgres for n8n history & Dashboard)
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # 3. The Nervous System (Redis for State/Locks)
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  # 4. The Brain (LangGraph + FastAPI)
  brain:
    build: ./brain
    restart: always
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_HOST=redis
    volumes:
      - ./brain:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


    # 5. The Dashboard
  dashboard:
    build: ./dashboard
    restart: always
    ports:
      - "8501:8501"
    links:
      - postgres